name: Build, Deploy, and Run Docker Container

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy, build, and restart Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /srv/vaquitas/config
            docker compose up -d
            cd ../clothing-search-automation
            git pull
            npm install
            npm run build
            pm2 restart npm
